# Generated by Django 5.2.3 on 2025-09-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, help_text='tons', max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='tons', max_digits=10)),
                ('min_distance', models.DecimalField(decimal_places=2, help_text='km', max_digits=10)),
                ('max_distance', models.DecimalField(decimal_places=2, help_text='km', max_digits=10)),
                ('base_distance', models.DecimalField(decimal_places=2, help_text='km included in base price', max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='base price', max_digits=10)),
                ('price_per_extra_km', models.DecimalField(decimal_places=2, help_text='kes', max_digits=10)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pricing_rules', to='fullloads.vehicletype')),
            ],
            options={
                'unique_together': {('vehicle_type', 'min_weight', 'max_weight', 'min_distance', 'max_distance')},
            },
        ),
    ]
