# Generated by Django 5.2.3 on 2025-09-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeightTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='vehiclepricing',
            old_name='vehicle_type',
            new_name='vehicle',
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='extra_per_km',
            field=models.DecimalField(decimal_places=2, help_text='kes', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepricing',
            name='base_distance',
            field=models.DecimalField(decimal_places=2, help_text='km included in base price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepricing',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='base price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='fullloads.distanceband'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclepricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='fullloads.weighttier'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclepricing',
            unique_together={('vehicle', 'weight', 'band')},
        ),
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='max_distance',
        ),
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='min_distance',
        ),
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='min_weight',
        ),
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='price_per_extra_km',
        ),
    ]
