# Generated by Django 5.2.3 on 2025-10-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_driverlocation_driver'),
        ('fullloads', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='origin_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='accounts.office'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_latLng',
            field=models.CharField(max_length=70, null=True, verbose_name='sender latitude,longitude'),
        ),
    ]
