# Generated by Django 5.2.3 on 2025-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0004_booking_origin_office_booking_pickup_latlng'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='payment phone'),
        ),
    ]
