# Generated by Django 5.2.3 on 2025-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullloads', '0005_booking_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
