# Generated by Django 5.1.7 on 2025-04-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Admin', 'Admin'), ('Agent', 'Agent'), ('Driver', 'Driver')], default='Client', max_length=60, null=True),
        ),
    ]
