# Generated by Django 5.1.7 on 2025-05-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vehicle_registration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
