# Generated by Django 5.1.7 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_vehicle_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
