# Generated by Django 5.2.3 on 2025-07-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_partnerprofile_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='location',
            field=models.CharField(max_length=70, null=True, verbose_name='shop address'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='location_latLang',
            field=models.CharField(max_length=70, null=True, verbose_name='partner shop latitude,longitude'),
        ),
    ]
