# Generated by Django 5.2.3 on 2025-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='enable_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='office',
            name='max_pickup_km',
            field=models.DecimalField(decimal_places=2, default='5.00', help_text='Distance covered under base pickup fee.', max_digits=5),
        ),
        migrations.AddField(
            model_name='office',
            name='pickup_discount_percent',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Discount (%) on intracity pickup fee for intercounty deliveries.', max_digits=5),
        ),
    ]
