# Generated by Django 5.2.3 on 2025-09-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_office_enable_pickup_office_max_pickup_km_and_more'),
        ('corporate', '0004_remove_corporateaccount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='corporate_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_users', to='corporate.corporateoffice'),
        ),
    ]
