# Generated by Django 5.2.3 on 2025-09-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_corporate_office'),
        ('corporate', '0005_alter_corporateroutepricing_corporate_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='corporate_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_office', to='corporate.corporateoffice'),
        ),
    ]
