# Generated by Django 5.2.3 on 2025-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_driverlocation_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='intracity_radius_km',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Max intracity delivery coverage in km.', max_digits=6),
        ),
        migrations.AddField(
            model_name='office',
            name='is_intracity_centre',
            field=models.BooleanField(default=False, help_text='Mark the office as the central point for intracity deliveries in the region.'),
        ),
    ]
