# Generated by Django 5.1.7 on 2025-04-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='county',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='subcounty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
