# Generated by Django 5.1.7 on 2025-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_location_warehouse_county_warehouse_subcounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
