# Generated by Django 5.1.7 on 2025-04-16 07:16

import apps.logistics.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_warehouse_latitude_alter_warehouse_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delivery_type', models.CharField(blank=True, max_length=60, null=True)),
                ('freight_type', models.CharField(blank=True, max_length=60, null=True)),
                ('fragile', models.CharField(blank=True, max_length=30, null=True)),
                ('urgent', models.CharField(blank=True, max_length=30, null=True)),
                ('length', models.CharField(blank=True, max_length=30, null=True)),
                ('width', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('sender_fullname', models.CharField(blank=True, max_length=60, null=True)),
                ('sender_email', models.CharField(blank=True, max_length=60, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('pickup_datetime', models.CharField(blank=True, max_length=60, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('recipient_fullname', models.CharField(blank=True, max_length=60, null=True)),
                ('recipient_email', models.CharField(blank=True, max_length=60, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('recipient_location', models.CharField(blank=True, max_length=60, null=True)),
                ('order_id', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_details', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='logistics.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.logistics.models.ImagePath)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logistics.order')),
            ],
        ),
    ]
