# Generated by Django 5.1.7 on 2025-04-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_order_orderdetails_orderimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_details',
            new_name='order_details_id',
        ),
    ]
