# Generated by Django 5.1.7 on 2025-04-17 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_rename_order_details_orderdetails_order_details_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('waybill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('delivery_stage', models.CharField(blank=True, max_length=70, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderWaybill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.order')),
                ('waybill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.waybill')),
            ],
        ),
    ]
