# Generated by Django 5.1.7 on 2025-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_waybill_orderwaybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waybill',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
