# Generated by Django 5.1.7 on 2025-04-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_waybill_assigned_to_waybill_is_delivered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderWaybill',
            new_name='WaybillOrders',
        ),
        migrations.RenameField(
            model_name='waybill',
            old_name='is_delivered',
            new_name='is_completed',
        ),
    ]
