# Generated by Django 5.1.7 on 2025-04-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_rename_orderwaybill_waybillorders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybillorders',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybillorders', to='logistics.order'),
        ),
        migrations.AlterField(
            model_name='waybillorders',
            name='waybill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='logistics.waybill'),
        ),
    ]
