# Generated by Django 5.1.7 on 2025-04-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_waybillorders_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybillorders',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='logistics.order'),
        ),
    ]
