# Generated by Django 5.1.7 on 2025-04-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_waybillorders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybillorders',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybillorders', to='logistics.order'),
        ),
    ]
