# Generated by Django 5.1.7 on 2025-04-19 05:00

import apps.logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_waybillorders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='barcode_svg',
            field=models.FileField(blank=True, null=True, upload_to=apps.logistics.models.barcodesPath),
        ),
    ]
