# Generated by Django 5.1.7 on 2025-04-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_waybill_barcode_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
