# Generated by Django 5.1.7 on 2025-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_alter_orderdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='delivery_stage',
            field=models.CharField(blank=True, default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='delivery_status',
            field=models.CharField(blank=True, default='UPDATING ...', max_length=200, null=True),
        ),
    ]
