# Generated by Django 5.1.7 on 2025-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_alter_orderdetails_delivery_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='assigned_pickupto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
