# Generated by Django 5.1.7 on 2025-04-25 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_orderdetails_assigned_pickupto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('waybill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.waybill')),
            ],
        ),
    ]
