# Generated by Django 5.1.7 on 2025-04-25 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_shipmentleg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentleg',
            name='waybill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipmentlegs', to='logistics.waybill'),
        ),
    ]
