# Generated by Django 5.1.7 on 2025-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_alter_shipmentleg_waybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentleg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentleg',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
