# Generated by Django 5.1.7 on 2025-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_shipmentleg_created_at_shipmentleg_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='urgent',
            new_name='urgency',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_latLang',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_latLang',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
