# Generated by Django 5.1.7 on 2025-05-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_rename_urgent_order_urgency_order_pickup_latlang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
