# Generated by Django 5.1.7 on 2025-05-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_order_package_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pickup_latLang',
            new_name='pickup_latLng',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='recipient_latLang',
            new_name='recipient_latLng',
        ),
    ]
