# Generated by Django 5.1.7 on 2025-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_rename_pickup_latlang_order_pickup_latlng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
