# Generated by Django 5.1.7 on 2025-05-05 01:53

import apps.logistics.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_stage', models.CharField(blank=True, max_length=70, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=70, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('barcode_svg', models.FileField(blank=True, null=True, upload_to=apps.logistics.models.barcodesPath)),
            ],
        ),
        migrations.RemoveField(
            model_name='waybillorders',
            name='waybill',
        ),
        migrations.RemoveField(
            model_name='shipmentleg',
            name='waybill',
        ),
        migrations.RemoveField(
            model_name='waybillorders',
            name='order',
        ),
        migrations.AddField(
            model_name='shipmentleg',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipmentlegs', to='logistics.shipment'),
        ),
        migrations.CreateModel(
            name='ShipmentItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='logistics.order')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='logistics.shipment')),
            ],
        ),
        migrations.DeleteModel(
            name='Waybill',
        ),
        migrations.DeleteModel(
            name='WaybillOrders',
        ),
    ]
