# Generated by Django 5.1.7 on 2025-05-05 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_shipment_remove_waybillorders_waybill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_stages_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipmentleg',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='logistics.shipment'),
        ),
    ]
