# Generated by Django 5.1.7 on 2025-05-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0028_shipment_shipment_stages_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment_stages_count',
            new_name='total_shipment_stages',
        ),
        migrations.AddField(
            model_name='shipment',
            name='completed_shipment_stages',
            field=models.IntegerField(default=0),
        ),
    ]
