# Generated by Django 5.1.7 on 2025-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0029_rename_shipment_stages_count_shipment_total_shipment_stages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentleg',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
