# Generated by Django 5.1.7 on 2025-05-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0030_shipmentleg_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitems',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.shipment'),
        ),
    ]
