# Generated by Django 5.1.7 on 2025-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0032_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
