# Generated by Django 5.1.7 on 2025-05-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0033_route_created_at_route_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.route'),
        ),
    ]
