# Generated by Django 5.1.7 on 2025-05-08 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0035_shipment_shipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentleg',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.route'),
        ),
    ]
