# Generated by Django 5.1.7 on 2025-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0036_alter_shipmentleg_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentleg',
            name='status',
            field=models.CharField(blank=True, default='PROCESSING', max_length=50, null=True),
        ),
    ]
