# Generated by Django 5.1.7 on 2025-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0037_alter_shipmentleg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='partner_sharing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
