# Generated by Django 5.1.7 on 2025-05-10 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0038_shipment_partner_shipment_partner_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='partner_sharing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.route'),
        ),
    ]
