# Generated by Django 5.1.7 on 2025-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0040_alter_shipment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
