# Generated by Django 5.1.7 on 2025-05-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0043_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
