# Generated by Django 5.1.7 on 2025-04-23 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
