# Generated by Django 5.2.3 on 2025-06-30 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0002_remove_package_delivered_remove_package_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('packages', models.ManyToManyField(related_name='invoices', to='deliveries.package')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-PESA'), ('airtel_money', 'Airtel Money'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash Payment')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=100)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.invoice')),
                ('received_by', models.ForeignKey(blank=True, help_text='Staff who confirmed the cash payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_cash_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
