# Generated by Django 5.1.7 on 2025-05-20 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
