# Generated by Django 5.2.3 on 2025-07-10 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_shipment_destination_office_shipment_origin_office'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='packages',
        ),
        migrations.AddField(
            model_name='invoice',
            name='package',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='deliveries.package'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='unpaid', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
