# Generated by Django 5.2.3 on 2025-10-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_invoice_is_paid_remove_invoice_packages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
