# Generated by Django 5.1.7 on 2025-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_amount_paid_invoice_due_date_invoice_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
    ]
