# Generated by Django 5.2.3 on 2025-10-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_created_at_payment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='paymentslog',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.invoice'),
        ),
    ]
