# Generated by Django 5.2.3 on 2025-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_invoice_parent_invoice_consolidatedinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedinvoice',
            name='consolidated_invoice_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
