# Generated by Django 5.2.3 on 2025-11-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_consolidatedinvoice_consolidated_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedinvoice',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('consolidated', 'consolidated')], default='consolidated', max_length=60, null=True),
        ),
    ]
