# Generated by Django 5.2.3 on 2025-06-30 10:39

import apps.deliveries.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique ID')),
                ('package_id', models.CharField(max_length=100, null=True, unique=True)),
                ('package_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('delivery_type', models.CharField(choices=[('intra_city', 'Intra-City'), ('inter_county', 'Inter-County'), ('international', 'International')], max_length=20, verbose_name='delivery type')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='fragile')),
                ('urgency', models.CharField(max_length=60, verbose_name='urgency')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='length')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='height')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='weight')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='pickup date time')),
                ('description', models.TextField(verbose_name='description')),
                ('fees', models.DecimalField(decimal_places=6, max_digits=15, null=True, verbose_name='fee charged')),
                ('image', models.ImageField(null=True, upload_to=apps.deliveries.models.UserPackageImgPath, verbose_name='package image')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='sender phone')),
                ('sender_address', models.CharField(max_length=255, verbose_name='sender address')),
                ('sender_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='sender latitude')),
                ('sender_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='sender longitude')),
                ('recipient_name', models.CharField(max_length=60, verbose_name='recipient name')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='recipient phone')),
                ('recipient_address', models.CharField(max_length=255, verbose_name='recipient location')),
                ('recipient_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='recipient latitude')),
                ('recipient_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='recipient longitude')),
                ('delivery_stage_count', models.PositiveIntegerField(default=1)),
                ('current_stage', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=60)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_packages', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_packages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sender name')),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.packagetype', verbose_name='package type')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_id', models.CharField(max_length=100, null=True, unique=True)),
                ('shipment_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('shipment_type', models.CharField(choices=[('delivery', 'Delivery to Recipient'), ('pickup', 'Pickup to Office'), ('transfer', 'Office to Office Transfer')], max_length=60)),
                ('status', models.CharField(default='created', max_length=50)),
                ('delivery_stage_count', models.PositiveIntegerField(default=1)),
                ('current_stage', models.PositiveIntegerField(default=1)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('qrcode_svg', models.FileField(null=True, upload_to=apps.deliveries.models.ShipmentQRPath)),
                ('courier', models.ForeignKey(limit_choices_to={'role__in': ['driver', 'partner_rider']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('returned', 'Returned to Office'), ('failed', 'Delivery Failed')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_packages', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.package')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'package')},
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='packages',
            field=models.ManyToManyField(related_name='shipments', through='deliveries.ShipmentPackage', to='deliveries.package'),
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status_update', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='deliveries.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='HandOver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('handover_type', models.CharField(choices=[('package', 'Package'), ('shipment', 'Shipment')], max_length=10)),
                ('stage_number', models.PositiveIntegerField()),
                ('is_partner', models.BooleanField(default=False)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ManyToManyField(blank=True, related_name='handover_confirmed', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_from', to=settings.AUTH_USER_MODEL)),
                ('to_users', models.ManyToManyField(related_name='handover_to', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.shipment')),
            ],
            options={
                'unique_together': {('handover_type', 'item_id', 'stage_number')},
            },
        ),
    ]
