# Generated by Django 5.2.3 on 2025-06-30 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='package',
            name='receiver_signature',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.AddField(
            model_name='package',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_name',
            field=models.CharField(max_length=255, null=True, verbose_name='sender name'),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='receiver_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
