# Generated by Django 5.2.3 on 2025-07-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_remove_package_delivered_remove_package_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntraCityPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_surcharge', models.DecimalField(decimal_places=4, default=0.0, help_text='Optional surcharge per kg for packages', max_digits=12)),
                ('per_km_extra_price', models.DecimalField(decimal_places=4, default=0.0, help_text='Price per km beyond the last tier', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('parcel', 'Parcel'), ('package', 'Package')], max_length=50, unique=True)),
                ('max_length', models.PositiveIntegerField()),
                ('max_width', models.PositiveIntegerField()),
                ('max_height', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='UrgencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('surcharge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percentage')], default='fixed', max_length=10)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, help_text='If percentage, use 10 for 10%', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='requires_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IntracityPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_km', models.FloatField()),
                ('to_km', models.FloatField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pricing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='deliveries.intracitypricingrule')),
            ],
            options={
                'ordering': ['from_km'],
            },
        ),
        migrations.AddField(
            model_name='intracitypricingrule',
            name='size_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.sizecategory'),
        ),
        migrations.CreateModel(
            name='InterCountyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_volumetric_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercounty_destination', to='deliveries.county')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercounty_origin', to='deliveries.county')),
                ('size_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.sizecategory')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='size_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.sizecategory'),
        ),
        migrations.AlterField(
            model_name='package',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.urgencylevel', verbose_name='urgency'),
        ),
    ]
