# Generated by Django 5.2.3 on 2025-07-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_package_destination_office_package_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
