# Generated by Django 5.2.3 on 2025-07-09 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_package_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='recipient_lat',
        ),
        migrations.RemoveField(
            model_name='package',
            name='recipient_lng',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender_lat',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender_lng',
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_latLng',
            field=models.CharField(default=django.utils.timezone.now, max_length=70, verbose_name='sender latitude,longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='sender_latLng',
            field=models.CharField(default=django.utils.timezone.now, max_length=70, verbose_name='sender latitude,longitude'),
            preserve_default=False,
        ),
    ]
