# Generated by Django 5.2.3 on 2025-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_remove_package_recipient_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipient_latLng',
            field=models.CharField(max_length=70, verbose_name='recipient latitude,longitude'),
        ),
    ]
