# Generated by Django 5.2.3 on 2025-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_alter_package_recipient_latlng'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntraCityPackagePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extra_km_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='IntraCityParcelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('max_distance_km', models.PositiveIntegerField(default=35)),
                ('base_km', models.PositiveIntegerField(default=5)),
                ('base_price', models.DecimalField(decimal_places=2, default=350.0, max_digits=10)),
                ('extra_price_per_km', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='intracitypricingtier',
            name='pricing_rule',
        ),
        migrations.DeleteModel(
            name='IntraCityPricingRule',
        ),
        migrations.DeleteModel(
            name='IntracityPricingTier',
        ),
    ]
