# Generated by Django 5.2.3 on 2025-07-10 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_intracitypackagepricing_intracityparcelpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCountyPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercounty_destination', to='deliveries.county')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercounty_origin', to='deliveries.county')),
                ('size_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.sizecategory')),
            ],
        ),
        migrations.DeleteModel(
            name='InterCountyPrice',
        ),
    ]
