# Generated by Django 5.2.3 on 2025-07-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_office_description'),
        ('deliveries', '0009_intercountypricingtier_delete_intercountyprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCountyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_weight_limit', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destinations', models.ManyToManyField(related_name='intercounty_route_destinations', to='accounts.office')),
                ('origins', models.ManyToManyField(related_name='intercounty_route_origins', to='accounts.office')),
                ('size_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.sizecategory')),
            ],
        ),
        migrations.CreateModel(
            name='InterCountyWeightTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='deliveries.intercountyroute')),
            ],
        ),
        migrations.DeleteModel(
            name='InterCountyPricingTier',
        ),
    ]
