# Generated by Django 5.2.3 on 2025-07-10 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_office_description'),
        ('deliveries', '0010_intercountyroute_intercountyweighttier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMileDeliveryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_within_km', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
            ],
        ),
    ]
