# Generated by Django 5.2.3 on 2025-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_lastmiledeliverypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='requires_last_mile',
            field=models.BooleanField(default=False, help_text="If True, deliver to recipient's door. Else recipient picks from destination office."),
        ),
    ]
