# Generated by Django 5.2.3 on 2025-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_package_requires_last_mile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='requires_handover',
            field=models.BooleanField(default=False),
        ),
    ]
