# Generated by Django 5.2.3 on 2025-07-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_office_description'),
        ('deliveries', '0013_shipment_requires_handover'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_destination', to='accounts.office'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_origin', to='accounts.office'),
        ),
    ]
