# Generated by Django 5.2.3 on 2025-07-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_image'),
        ('deliveries', '0014_shipment_destination_office_shipment_origin_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='handover',
            unique_together={('handover_type', 'stage_number')},
        ),
        migrations.RemoveField(
            model_name='shipmenttracking',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='item_id',
        ),
        migrations.CreateModel(
            name='ShipmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('driver_accepted', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['driver', 'partner_rider']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_from', to='accounts.office')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='deliveries.shipment')),
                ('to_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_to', to='accounts.office')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('shipment', 'stage_number')},
            },
        ),
    ]
