# Generated by Django 5.2.3 on 2025-07-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0015_alter_handover_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='shipment_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='deliveries.shipmentstage'),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='shipment_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='deliveries.shipmentstage'),
        ),
    ]
