# Generated by Django 5.2.3 on 2025-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_handover_shipment_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentstage',
            name='handover_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
