# Generated by Django 5.2.3 on 2025-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0018_alter_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intracitypackagepricing',
            name='extra_km_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
