# Generated by Django 5.2.3 on 2025-07-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_image'),
        ('deliveries', '0019_alter_intracitypackagepricing_extra_km_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmiledeliverypolicy',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_mile_policy', to='accounts.office'),
        ),
    ]
