# Generated by Django 5.2.3 on 2025-07-26 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_office_enable_pickup_office_max_pickup_km_and_more'),
        ('deliveries', '0020_alter_lastmiledeliverypolicy_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentpackage',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='delivery_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_packages', to='deliveries.shipmentstage'),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='delivery_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='pickup_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.partnerprofile'),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='pickup_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_packages', to='deliveries.shipmentstage'),
        ),
        migrations.AddField(
            model_name='shipmentpackage',
            name='pickup_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('delivery', 'Delivery to Recipient'), ('pickup', 'Pickup to Office'), ('transfer', 'Office to Office Transfer'), ('complete', 'Pickup and Deliver to Recipient')], max_length=60),
        ),
    ]
