# Generated by Django 5.2.3 on 2025-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0021_shipmentpackage_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='confirm_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ASSIGNED', 'ASSIGNED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED'), ('RECEIVED', 'RECEIVED'), ('RETURNED', 'RETURNED'), ('CANCELLED', 'CANCELLED'), ('HANDOVER', 'HANDOVER')], default='PENDING', max_length=30),
        ),
    ]
