# Generated by Django 5.2.3 on 2025-09-02 09:24

import apps.deliveries.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0023_vehicletype_vehiclepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=apps.deliveries.models.packageAttachmentsPath)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_attachments', to='deliveries.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='deliveries.package')),
            ],
        ),
    ]
