# Generated by Django 5.2.3 on 2025-09-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0024_packageattachment_packageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.vehicletype'),
        ),
    ]
