# Generated by Django 5.2.3 on 2025-09-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0025_package_vehicle_type'),
        ('fullloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fullloads.vehicletype'),
        ),
        migrations.DeleteModel(
            name='VehiclePricing',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
