# Generated by Django 5.2.3 on 2025-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0027_proofofdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('delivered', 'delivered'), ('received', 'received'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('handover', 'handover'), ('completed', 'completed')], default='pending', max_length=30),
        ),
    ]
