# Generated by Django 5.2.3 on 2025-10-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0028_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payment_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='payment phone'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.packagetype', verbose_name='package type'),
        ),
        migrations.AlterField(
            model_name='package',
            name='urgency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.urgencylevel', verbose_name='urgency'),
        ),
    ]
