# Generated by Django 5.2.3 on 2025-10-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0029_package_payment_phone_alter_package_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='payment phone'),
        ),
    ]
