# Generated by Django 5.2.3 on 2025-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0030_alter_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickup_now',
            field=models.BooleanField(default=False),
        ),
    ]
