# Generated by Django 5.2.3 on 2025-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0032_shipment_destination_latlng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('delivery', 'Delivery to Recipient'), ('pickup', 'Pickup to Office'), ('transfer', 'Office to Office Transfer'), ('intra_city', 'Pickup and Deliver to Recipient')], max_length=60),
        ),
        migrations.AlterField(
            model_name='shipmentstage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('delivered', 'delivered'), ('received', 'received'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('handover', 'handover'), ('completed', 'completed')], default='assigned', max_length=30),
        ),
    ]
