# Generated by Django 5.2.3 on 2025-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0033_alter_shipment_shipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
