# Generated by Django 5.2.3 on 2025-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0034_package_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('in_office', 'in_office'), ('delivered', 'delivered'), ('received', 'received'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('handover', 'handover'), ('completed', 'completed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentstage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('in_office', 'in_office'), ('delivered', 'delivered'), ('received', 'received'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('handover', 'handover'), ('completed', 'completed')], default='assigned', max_length=30),
        ),
    ]
