# Generated by Django 5.2.3 on 2025-10-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_office_intracity_radius_km_and_more'),
        ('deliveries', '0035_alter_package_status_alter_shipmentstage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intercountyroute',
            options={'verbose_name': 'Inter-County Route', 'verbose_name_plural': 'Inter-County Routes'},
        ),
        migrations.AlterModelOptions(
            name='intercountyweighttier',
            options={'ordering': ['min_weight'], 'verbose_name': 'Inter-County Weight Tier', 'verbose_name_plural': 'Inter-County Weight Tiers'},
        ),
        migrations.AddField(
            model_name='intracityparcelpolicy',
            name='office',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intracity_policy', to='accounts.office'),
        ),
        migrations.AddField(
            model_name='intracityparcelpolicy',
            name='radius_km',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'mpesa'), ('card', 'card')], default='mpesa', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmentpackage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('in_office', 'in_office'), ('delivered', 'delivered'), ('returned', 'Returned to Office'), ('cancelled', 'cancelled')], default='pending', max_length=30),
        ),
    ]
