# Generated by Django 5.2.3 on 2025-10-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0036_alter_intercountyroute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofdelivery',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_proofs', to='deliveries.package'),
        ),
        migrations.AlterField(
            model_name='proofofdelivery',
            name='image_pdf',
            field=models.FileField(upload_to='deliveries/proofs'),
        ),
        migrations.AlterField(
            model_name='proofofdelivery',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='deliveries.shipment'),
        ),
    ]
