# Generated by Django 5.2.3 on 2025-10-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_office_intracity_radius_km_and_more'),
        ('deliveries', '0037_proofofdelivery_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.office'),
        ),
    ]
