# Generated by Django 5.2.3 on 2025-10-25 14:14

import apps.deliveries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0038_package_current_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='qrcode_svg',
            field=models.FileField(null=True, upload_to=apps.deliveries.models.PackageQRPath),
        ),
    ]
