# Generated by Django 5.2.3 on 2025-10-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0039_package_qrcode_svg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageitem',
            old_name='name',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='packageitem',
            name='destination_latLng',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='price',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
