# Generated by Django 5.2.3 on 2025-10-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0040_rename_name_packageitem_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='requires_packaging',
            field=models.BooleanField(default=False),
        ),
    ]
