# Generated by Django 5.2.3 on 2025-10-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0041_package_requires_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofofdelivery',
            name='image_pdf',
        ),
        migrations.RemoveField(
            model_name='proofofdelivery',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='proofofdelivery',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='identity_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
