# Generated by Django 5.2.3 on 2025-10-27 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0042_remove_proofofdelivery_image_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofdelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
