# Generated by Django 5.2.3 on 2025-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0044_proofofdelivery_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('with_courier', 'with_courier'), ('in_office', 'in_office'), ('delivered', 'delivered'), ('received', 'received'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('handover', 'handover'), ('completed', 'completed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentpackage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('with_courier', 'with_courier'), ('in_office', 'in_office'), ('delivered', 'delivered'), ('returned', 'Returned to Office'), ('cancelled', 'cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentstage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_transit', 'in_transit'), ('with_courier', 'with_courier'), ('in_office', 'in_office'), ('delivered', 'delivered'), ('received', 'received'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('handover', 'handover'), ('completed', 'completed')], default='assigned', max_length=30),
        ),
    ]
