# Generated by Django 5.2.3 on 2025-11-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0045_alter_package_status_alter_shipmentpackage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='no_items',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='recipient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='recipient_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
