# Generated by Django 5.2.3 on 2025-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0046_packageitem_date_created_packageitem_no_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='recipient location'),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_latLng',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='recipient latitude,longitude'),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='recipient name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='recipient phone'),
        ),
    ]
