# Generated by Django 5.2.3 on 2025-11-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_office_intracity_radius_km_and_more'),
        ('deliveries', '0047_alter_package_recipient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intracitypackagepricing',
            name='base_price',
        ),
        migrations.AddField(
            model_name='intracitypackagepricing',
            name='max_distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='intracitypackagepricing',
            name='min_distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='intracitypackagepricing',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.office'),
        ),
        migrations.AddField(
            model_name='intracitypackagepricing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
