# Generated by Django 5.2.3 on 2025-10-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_wallettransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='completed_deliveries_since_withdrawal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_withdrawal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
