# Generated by Django 5.2.3 on 2025-09-03 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_office_enable_pickup_office_max_pickup_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=15, null=True)),
                ('lat_lng', models.CharField(max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=15, null=True)),
                ('lat_lng', models.CharField(max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_head_office', models.BooleanField(default=False)),
                ('corporate_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_office', to='corporate.corporateaccount')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_links', to='accounts.office')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateRoutePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, help_text='kgs', max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='kgs', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='kes', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corporate_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corporate.corporateoffice')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_pricing_destination', to='accounts.office')),
                ('origin_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_pricing_origin', to='accounts.office')),
            ],
            options={
                'unique_together': {('corporate_account', 'origin_office', 'destination_office', 'min_weight', 'max_weight')},
            },
        ),
    ]
