# Generated by Django 5.2.3 on 2025-09-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateoffice',
            name='label',
        ),
    ]
