# Generated by Django 5.2.3 on 2025-09-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_remove_corporateoffice_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateaccount',
            name='lat_lng',
        ),
    ]
