# Generated by Django 5.2.3 on 2025-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_remove_corporateaccount_lat_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='corporateoffice',
            name='office',
        ),
        migrations.AddField(
            model_name='corporateoffice',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
