# Generated by Django 5.2.3 on 2025-09-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_corporate_office'),
        ('corporate', '0004_remove_corporateaccount_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateroutepricing',
            name='corporate_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='corporate.corporateoffice'),
        ),
        migrations.CreateModel(
            name='CorporateRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_pricing_destination', to='accounts.office')),
                ('origin_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_pricing_origin', to='accounts.office')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='corporateroutepricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='corporateroutepricing',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_tiers', to='corporate.corporateroute'),
        ),
        migrations.AlterUniqueTogether(
            name='corporateroutepricing',
            unique_together={('corporate_account', 'route', 'min_weight', 'max_weight')},
        ),
        migrations.RemoveField(
            model_name='corporateroutepricing',
            name='destination_office',
        ),
        migrations.RemoveField(
            model_name='corporateroutepricing',
            name='origin_office',
        ),
    ]
